# Generated by Django 6.1.1 on 2026-09-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hello', '0004_profile_intrests_alter_education_degree_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
